version: "3"
services:
  etcd-1:
    image: gcr.io/etcd-development/etcd:latest
    entrypoint: /usr/local/bin/etcd
    volumes:
      - etcd_data:/data/
    deploy:
      mode: global
    command:
            - '--name=etcd-1'
            - '--data-dir=/data/'
            - '--initial-advertise-peer-urls=http://etcd-1:2380'
            - '--listen-peer-urls=http://0.0.0.0:2380'
            - '--listen-client-urls=http://0.0.0.0:2379'
            - '--advertise-client-urls=http://etcd-1:2379'
            - '--initial-cluster=etcd-1=http://etcd-1:2380'
            - '--initial-cluster-state=new'
    networks:
      - etcd
    restart: unless-stopped

  etcd-viewer:
    image: nikfoundas/etcd-viewer
    deploy:
      mode: global
    networks:
      - etcd
    ports:
      - 8081:8080/tcp
    
networks:
  etcd:

volumes:
  etcd_data: