version: '3.2'

services:
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: ingress
    networks:
      - portainer_agent
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
  webui:
    image: portainer/portainer
    networks:
      - portainer_agent
    deploy:
      mode: global
    ports:
    - target: 9000
      published: 9000 
      protocol: tcp
      mode: host



networks:
  portainer_agent:
    driver: overlay
    attachable: true
