version: "3"
services:
  rabbitmq-master:
    image: rabbitmq:3-management
    networks:
      - rabbitmq_overlay
    ports:
      - "15672:15672/tcp"
    restart: unless-stopped
    deploy:
      mode: global
    environment:
    - "RABBITMQ_ERLANG_COOKIE=YOLO_424242"
    - "RABBITMQ_NODENAME=master@rabbitmq-master"
    
  rabbitmq-nodes:
    image: rabbitmq:3-node
    networks:
      - rabbitmq_overlay
    restart: "no"
    environment:
    - "CLUSTER_NAME=master@rabbitmq-master"
    - "RABBITMQ_ERLANG_COOKIE=YOLO_424242"
    
    
networks:
  rabbitmq_overlay:
    external:
      name: rabbitmq_overlay