version: "3"
services:
  rabbitmq-master:
    image: lleonard/rabbitmq:latest
    networks:
      - rabbitmq_overlay
      - consul_consul
    ports:
      - "15672:15672/tcp"
      - "5672:5672/tcp"
    restart: unless-stopped
    deploy:
      mode: replicated
    environment:
    - "RABBITMQ_ERLANG_COOKIE=YOLO_424242"
    - "RABBITMQ_NODENAME=master@rabbitmq-master"
    
    
networks:
  rabbitmq_overlay:
    external:
      name: rabbitmq_overlay
  consul_consul:
    external:
      name: consul_consul