version: "3.2"

services:
  plex:
    image: plexinc/pms-docker
    networks:
      - internal
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=*****
      - ADVERTISE_IP=http://192.168.0.10:32400/
    volumes:
      - "/mnt/MyPassport/TV_BOX/LIBRARIES:/libraries"
      - "/home/lleonard/plex-config:/config"
    restart: unless-stopped
  
  sonarr:
    image: linuxserver/sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    networks:
      - internal
    volumes:
      - /home/lleonard/tv_box/sonarr_config:/config
      - /mnt/MyPassport/TV_BOX/LIBRARIES:/tv
      - /home/lleonard/tv_box/downloads:/tv_box/download/
    ports:
      - 8989:8989/tcp
    restart: unless-stopped
    
  sabnzbd:
    image: sabnzbd/sabnzbd
    environment:
      - "SABNZBD_UID=1000"
      - "SABNZBD_GID=1000"
    volumes:
        - /home/lleonard/tv_box/sabnzbd_config/:/datadir
        - /home/lleonard/tv_box/downloads/:/tv_box/download/
    ports:
        - 8080:8080/tcp
    networks:
      - internal
    restart: always
    
networks:
  internal: